In [1]:
import numpy as np

In [3]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 15], [61, 1], [0, 49]])
X

array([[25, 15],
       [61,  1],
       [ 0, 49]])

In [5]:
# tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [7]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([25, 61,  0])

In [8]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([61,  1])

In [9]:
# 2 ulangi soal nomor 1 menggunakan pytorch
import torch

In [10]:
X_pt = torch.tensor([[25, 15], [61, 1], [0, 49]])
X_pt

tensor([[25, 15],
        [61,  1],
        [ 0, 49]])

In [11]:
X_pt.shape

torch.Size([3, 2])

In [12]:
# seluruh elemen kolom pertama
X_pt[:,0]

tensor([25, 61,  0])

In [13]:
# seluruh elemen baris kedua
X_pt[1,:]

tensor([61,  1])

In [14]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [16]:
X_tf = tf.Variable([[25, 15], [61, 1], [0, 49]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25, 15],
       [61,  1],
       [ 0, 49]], dtype=int32)>

In [17]:
X_tf.shape

TensorShape([3, 2])

In [18]:
# seluruh elemen kolom pertama
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 61,  0], dtype=int32)>

In [19]:
# seluruh elemen baris kedua
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([61,  1], dtype=int32)>